osx_image: xcode10.3
language: swift

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GrayCore.xcworkspace -scheme GrayCore-Example -sdk iphonesimulator12.4 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint